CREATE SCHEMA `myorder` DEFAULT CHARACTER SET utf8mb4;

use myorder;


        `ADDRESS`,
        `WECHAT`,
        `CREATETIME`,
        `LEVEL`,
        `UPDATETIME`

CREATE TABLE `t_user` (
    `ID` VARCHAR(100) NOT NULL COMMENT '自增长主键id',
    `USERNAME` VARCHAR(100) NOT NULL COMMENT '用户名',
    `CELLPHONE` VARCHAR(100) NOT NULL COMMENT '手机号',
    `ADDRESS` VARCHAR(100) NOT NULL COMMENT '地址',
    `WECHAT` VARCHAR(100) NOT NULL COMMENT '微信号',
    `LEVEL` TINYINT(5) NOT NULL COMMENT '等级',
    `CREATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATETIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COMMENT='用户表';
